production:
        adapter: sqlite3
        database: db/production.sqlite3
        pool: 5
        timeout: 5000

production:
        adapter: mysql2
        encoding: utf8
        reconnect: false
        pool: 5
        username: username
        password: pass
        host: localhost

